import type { MockOrder } from "@/features/home/types";

export const MOCK_ORDERS: MockOrder[] = [
  {
    id: "1",
    orderNumber: "#ORD-01",
    customerName: "Abdulaziz Al-Dosari",
    customerPhone: "+966 514 111 001",
    handlerName: "Sara Ahmed",
    createdDate: "Tuesday, 12 January 2026",
    createdTime: "10:24 AM",
    source: "eform",
    executionDate: "Wednesday, 19 February 2026",
    status: "new",
  },
  {
    id: "2",
    orderNumber: "#ORD-02",
    customerName: "Noura Alharbi",
    customerPhone: "+966 512 222 014",
    handlerName: "Omar Ali",
    createdDate: "Monday, 11 January 2026",
    createdTime: "02:15 PM",
    source: "manual",
    executionDate: "Thursday, 20 February 2026",
    status: "new",
  },
  {
    id: "3",
    orderNumber: "#ORD-03",
    customerName: "Khalid Alotaibi",
    customerPhone: "+966 555 333 021",
    handlerName: "Layla Hassan",
    createdDate: "Sunday, 10 January 2026",
    createdTime: "09:05 AM",
    source: "eform",
    executionDate: "Friday, 21 February 2026",
    status: "new",
  },
  {
    id: "4",
    orderNumber: "#ORD-04",
    customerName: "Huda Mansour",
    customerPhone: "+966 501 444 088",
    handlerName: "Fahad Alotaibi",
    createdDate: "Saturday, 9 January 2026",
    createdTime: "04:40 PM",
    source: "manual",
    executionDate: "Monday, 23 February 2026",
    status: "new",
  },
  {
    id: "5",
    orderNumber: "#ORD-05",
    customerName: "Yousef Ibrahim",
    customerPhone: "+966 540 555 099",
    handlerName: "Maha Alharbi",
    createdDate: "Friday, 8 January 2026",
    createdTime: "11:30 AM",
    source: "eform",
    executionDate: "Tuesday, 24 February 2026",
    status: "new",
  },
];
